// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixlihssbyoheozemgnjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4bGloc3NieW9oZW96ZW1nbmpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNzU5OTAsImV4cCI6MjA1Njk1MTk5MH0.EFHkdngmfMVKQ5AusoYFJrUXx1B498tWrG6PF6-10U8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);